CREATE DATABASE MasterData;

USE MasterData;

CREATE TABLE product (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
productNumber VARCHAR(30) NOT NULL,
productName VARCHAR(30) NOT NULL,
isActive BOOLEAN,
createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT UC_product UNIQUE (id,productNumber)
);


CREATE TABLE price (
priceID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
productPrice FLOAT,
isActive BOOLEAN,
createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
productID int
);


ALTER TABLE price ADD FOREIGN KEY (productID) REFERENCES product(id);



CREATE DATABASE Order_;

USE Order_;

CREATE TABLE OrderHeader (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
orderNumber VARCHAR(30) NOT NULL,
productName VARCHAR(30) NOT NULL,
createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT UC_product UNIQUE (id,orderNumber)
);


CREATE TABLE OrderDetail (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
productNumber VARCHAR(30) NOT NULL,
productCount int,
productPrice FLOAT,
createdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
orderNumber int
);


ALTER TABLE OrderDetail ADD FOREIGN KEY (orderNumber) REFERENCES OrderHeader(id);
